In [1]:
import numpy as np
import pandas as pd
import pybedtools as pb

In [7]:
pb.filenames.example_filename('c.gff')

'/Users/umut/pyvenv/lib/python2.7/site-packages/pybedtools/test/data/c.gff'

In [14]:
annot = pd.read_csv('/Users/umut/Projects/CellCycle/data/AllTranscriptsSteinmetz.csv',',')

In [17]:
annot.sort_values(by =['chr','start'],inplace=True)

In [18]:
annot.head()

,ID,chr,strand,start,end,type,name,commonName,endConfidence,source
3633,ST3634,1,-,5076,6237,SUTs,SUT432,SUT432,bothEndsMapped,Manual
3634,ST3635,1,-,7277,9261,ORF-T,YAL067C,SEO1,bothEndsMapped,Manual
0,ST0001,1,+,9369,9601,SUTs,SUT001,SUT001,bothEndsMapped,Manual
3635,ST3636,1,-,10733,11141,CUTs,CUT436,CUT436,bothEndsMapped,Automatic
3636,ST3637,1,-,28085,29773,SUTs,SUT433,SUT433,bothEndsMapped,Manual

In [27]:
df = pd.DataFrame()
stride = 20
window_size = 500
for ch in np.arange(1,17):
    mn = np.min(annot.loc[annot['chr']==ch,'start'])
    mx = np.max(annot.loc[annot['chr']==ch,'end'])
    starts = np.arange(mn,mx,stride)
    df = df.append(pd.DataFrame({'chr':[ch]*len(starts),'start':starts,'end':starts+window_size}))

In [28]:
df

       chr     end   start
0        1    5576    5076
1        1    5596    5096
2        1    5616    5116
3        1    5636    5136
4        1    5656    5156
5        1    5676    5176
6        1    5696    5196
7        1    5716    5216
8        1    5736    5236
9        1    5756    5256
10       1    5776    5276
11       1    5796    5296
12       1    5816    5316
13       1    5836    5336
14       1    5856    5356
15       1    5876    5376
16       1    5896    5396
17       1    5916    5416
18       1    5936    5436
19       1    5956    5456
20       1    5976    5476
21       1    5996    5496
22       1    6016    5516
23       1    6036    5536
24       1    6056    5556
25       1    6076    5576
26       1    6096    5596
27       1    6116    5616
28       1    6136    5636
29       1    6156    5656
...    ...     ...     ...
45944   16  942261  941761
45945   16  942281  941781
45946   16  942301  941801
45947   16  942321  941821
45948   16  942341  941841
45949   16  942361  941861
45950   16  942381  941881
45951   16  942401  941901
45952   16  942421  941921
45953   16  942441  941941
45954   16  942461  941961
45955   16  942481  941981
45956   16  942501  942001
45957   16  942521  942021
45958   16  942541  942041
45959   16  942561  942061
45960   16  942581  942081
45961   16  942601  942101
45962   16  942621  942121
45963   16  942641  942141
45964   16  942661  942161
45965   16  942681  942181
45966   16  942701  942201
45967   16  942721  942221
45968   16  942741  942241
45969   16  942761  942261
45970   16  942781  942281
45971   16  942801  942301
45972   16  942821  942321
45973   16  942841  942341

[582931 rows x 3 columns]

In [29]:
df.shape

(582931, 3)